version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 20s
      timeout: 10s
      retries: 10
    networks:
      - app-network

  focusflow-backend:
    image: srividyagajjala/focusflow-backend:latest
    container_name: focusflow-backend
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    networks:
      - app-network

 focusflow-frontend:
  image: srividyagajjala/focusflow-frontend:latest
  container_name: focusflow-frontend
  ports:
    - "5173:5173"
  depends_on:
    - focusflow-backend
  environment:
    - VITE_API_URL=http://focusflow-backend:8080
  networks:
    - app-network


volumes:
  cassandra-data:

networks:
  app-network:
    driver: bridge
